Quaternion to Euler Angles Conversion Tests

In [4]:
#Import Necessary Libraries
import sys
!{sys.executable} -m pip install scipy
from scipy.spatial.transform import Rotation as R
import numpy as np
import random
import math

     |████████████████████████████████| 35.2 MB 380 kB/s eta 0:00:012   |██                              | 2.3 MB 8.6 MB/s eta 0:00:04     |██████▉                         | 7.5 MB 8.6 MB/s eta 0:00:04     |███████████                     | 12.1 MB 11.2 MB/s eta 0:00:03     |████████████████▎               | 17.9 MB 11.2 MB/s eta 0:00:02
     |████████████████████████████████| 19.8 MB 10.2 MB/s eta 0:00:01�████▏ | 18.7 MB 10.2 MB/s eta 0:00:01
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.


Rotation Method

In [65]:
def euler_to_quaternion(method, x, y, z):
    rotation = R.from_euler(method, [x,y,z], degrees=False)
    quaternion = rotation.as_quat()
    return quaternion

def quaternion_to_euler(method, quat):
    rotation = R.from_quat(quat)
    euler_angles = rotation.as_euler(method, degrees=False)
    return euler_angles



XYZ Rotation Testing

In [68]:
x = random.uniform(-(math.pi), (math.pi))
y = random.uniform(-(math.pi), (math.pi))
z = random.uniform(-(math.pi), (math.pi))
quaternion = euler_to_quaternion('xyz', x, y, z)

print('Original Euler angles: ')
print(x, y, z)
print('Associated Quaternion ([vector, scalar])')
print(quaternion)
print('\n')

print('Conversion back to Euler angles: ')
print(quaternion_to_euler('xyz', quaternion))




Original Euler angles: 
-0.23635666142074108 2.457809481713155 0.034582490810971755
Associated Quaternion ([vector, scalar])
[-0.05569959  0.93472758  0.11681935  0.33096093]


Conversion back to Euler angles: 
[ 2.90523599  0.68378317 -3.10701016]


ZYX Rotation Testing

In [74]:
x = random.uniform(-(math.pi), (math.pi))
y = random.uniform(-(math.pi), (math.pi))
z = random.uniform(-(math.pi), (math.pi))
quaternion = euler_to_quaternion('zyx', x, y, z)

print('Original Euler angles: ')
print(x, y, z)
print('Associated Quaternion ([vector, scalar])')
print(quaternion)
print('\n')

print('Conversion back to Euler angles: ')
print(quaternion_to_euler('zyx', quaternion))

Original Euler angles: 
1.6889840050393774 -0.8795492711911068 -1.1354701293215448
Associated Quaternion ([vector, scalar])
[-0.59148931  0.12538687  0.72240067  0.33549338]


Conversion back to Euler angles: 
[ 1.68898401 -0.87954927 -1.13547013]


Manual Conversion Based on NASA Article

In [92]:
def e_to_q(method, x, y, z):

    if method == 'xyz':

        r = math.cos(x*0.5)*math.cos(y*0.5)*math.cos(z*0.5)-math.sin(x*0.5)*math.sin(y*0.5)*math.sin(z*0.5)
        v1 = math.sin(x*0.5)*math.cos(y*0.5)*math.cos(z*0.5)+math.cos(x*0.5)*math.sin(y*0.5)*math.sin(z*0.5)
        v2 = math.cos(x*0.5)*math.sin(y*0.5)*math.cos(z*0.5)-math.sin(x*0.5)*math.cos(y*0.5)*math.sin(z*0.5)
        v3 = math.cos(x*0.5)*math.cos(y*0.5)*math.sin(z*0.5)+math.sin(x*0.5)*math.sin(y*0.5)*math.cos(z*0.5)

        return [v1, v2, v3, r]

    elif method == 'zyx':

        r = math.sin(x*0.5)*math.sin(y*0.5)*math.sin(z*0.5)+math.cos(x*0.5)*math.cos(y*0.5)*math.cos(z*0.5)
        v1 = math.sin(x*0.5)*math.cos(y*0.5)*math.cos(z*0.5)-math.cos(x*0.5)*math.sin(y*0.5)*math.sin(z*0.5)
        v2 = math.sin(x*0.5)*math.cos(y*0.5)*math.sin(z*0.5)+math.cos(x*0.5)*math.sin(y*0.5)*math.cos(z*0.5)
        v3 = math.cos(x*0.5)*math.cos(y*0.5)*math.sin(z*0.5)-math.sin(x*0.5)*math.sin(y*0.5)*math.cos(z*0.5)

        return [v1, v2, v3, r]

    elif method == 'xzy':

        r = math.sin(x*0.5)*math.sin(y*0.5)*math.sin(z*0.5)+math.cos(x*0.5)*math.cos(y*0.5)*math.cos(z*0.5)
        v1 = math.sin(x*0.5)*math.cos(y*0.5)*math.cos(z*0.5)-math.cos(x*0.5)*math.sin(y*0.5)*math.sin(z*0.5)
        v2 = math.cos(x*0.5)*math.sin(y*0.5)*math.cos(z*0.5)-math.sin(x*0.5)*math.cos(y*0.5)*math.sin(z*0.5)
        v3 = math.sin(x*0.5)*math.sin(y*0.5)*math.cos(z*0.5)+math.cos(x*0.5)*math.cos(y*0.5)*math.sin(z*0.5)

        return [v1, v2, v3, r]

    else:
        return 'Error'


def q_to_e(method, quat):

    v1 = quat[0]
    v2 = quat[1]
    v3 = quat[2]
    r = quat[3]

    if method == 'xyz':

        return True

    elif method == 'zyx':
        
        return True
    else:
        return 'Error'

    return false

Comparison of Two Methods 
Findings: 
SciPy "XYZ" = NASA "ZYX"
SciPy "ZYX" ?= NASA "XYZ" (The results of 2 vector components were swapped? Does this matter??)
SciPy "XZY" ?= NASA...

Need to check for conversion back. 

In [107]:
x0 = random.uniform(-(math.pi), (math.pi))
y0 = random.uniform(-(math.pi), (math.pi))
z0 = random.uniform(-(math.pi), (math.pi))
# SciPy rotation
quaternion1 = euler_to_quaternion('xyz', x0, y0, z0)
# Manual rotation
quaternion2 = e_to_q('zyx', x0, y0, z0)
print('Original Euler angles: ')
print(x0, y0, z0)
print('SciPy Associated Quaternion ([vector, scalar])')
print(quaternion1)
print('Manually Calculated Quaternion ([vector, scalar])')
print(quaternion2)

Original Euler angles: 
1.1657864976338495 2.5819550477214133 2.2368717544131647
SciPy Associated Quaternion ([vector, scalar])
[-0.65524715  0.48745268 -0.02384998  0.57660405]
Manually Calculated Quaternion ([vector, scalar])
[-0.6552471499416721, 0.48745268261442687, -0.023849978975637648, 0.576604052368847]
